name = "Qualia Quartz'z Quizzical Quandary"
author = "Qualia"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "316c9372451ffa9e1f3f5ba31ec22b83710b6ca06a2db317ba1d046df7a259cf"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.105"
