name = "Qualia Quartz'z Quizzical Quandary"
author = "Qualia"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09de1cdeb41c42d6937d6beb9e04c5395b4a6835946c529c809ae690813c81dc"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.105"
