name = "Qualia Quartz'z Quizzical Quandary"
author = "Qualia"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af3a0ed3237635919e0254619339c66e123f916d1f5ceec83d802c62568c3c96"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.105"
